global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'ecs'
    file_sd_configs:
      - files:
          - /prometheus/ecs_file_sd.yml
        refresh_interval: 1m