name: "Terraform Apply"

on:
  push:
    branches:
    - develop
    - main

jobs:

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Setup - Set env bucket"
        run: |
          case "${GITHUB_REF#refs/heads/}" in
            develop)
              export ENV=dev
              ;;
            main)
              export ENV=dev
              ;;
          esac
          find infra/ -type f -exec sed -i "s/BUCKETENVIRONMENT/$ENV/g" {} +

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.7.3

      - name: "Run - Terraform Init"
        run: |
          cd infra/03-services/
          terraform init -input=false
          cd ../../

      - name: "Run - Terraform Apply"
        id: apply
        run: |
          case "${GITHUB_REF#refs/heads/}" in
            develop)
              export ENV=dev
              ;;
            main)
              export ENV=dev
              ;;
          esac
          cd infra/03-services/
          terraform plan -var-file=../environments/$ENV.tfvars -input=false -no-color -out out.tf
          terraform apply -auto-approve -input=false -no-color out.tf
